version: '3'
services:
  hbase:
    image: bhargavnaik/hbase
    hostname: hbase
    ports:
      - 8080:8080
      - 8085:8085
      - 9090:9090
      - 9095:9095
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    volumes:
      - '~/work/docker-volumes:/data'
    depends_on:
      - zk
  zk:
    image: zookeeper:3.4.11
    hostname: zk
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - '~/work/docker-volumes/zookeeper/data:/data'
      - '~/work/docker-volumes/zookeeper/log:/datalog'  
